image: docker:stable 

services:
    - docker:dind

#Environment variables
variables:

  #MYSQL_ROOT_PASSWORD: root
 # MYSQL_DATABASE: 
  CONTAINER_IMAGE: registry.gitlab.com/Jimmy.exe/2019_assignment1_balducci_guidi
  #CONTAINER_RELEASE_IMAGE: registry.gitlab.com/Jimmy.exe/2019_assignment1_balducci_guidi:latest

#stages
  stages:
   - build


  build:
    stage: build
    script:
        - echo "Building"
        - echo $CI_JOB_TOKEN
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
        - docker build -t $CONTAINER_IMAGE .
        - docker push $CONTAINER_IMAGE




