image: docker:stable 

services:
    - docker:dind

#Environment variables
variables:
    CONTAINER_IMAGE: registry.gitlab.com/jiimmy.exe/2019_assignment1_balducci_guidi
    CONTAINER_RELEASE_IMAGE: registry.gitlab.com/jiimmy.exe/2019_assignment1_balducci_guidi:latest

#stages
stages:
    - build
    - verify
    - test-unit
    - release
    - deploy

build:
    stage: build
    script:
        - echo "Building"
        - echo $CI_JOB_TOKEN
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
        - docker build -t $CONTAINER_IMAGE .
        - docker push $CONTAINER_IMAGE
verify:
    stage: verify
    image: $CONTAINER_IMAGE
    script:
        - pylint userapp.py
        - allow_failure: true
        - pylint user_webapp.py
        - allow_failure: true
        - pylint back_database.py
        - pylint check_functions.py
    allow_failure: true
    
    
    
    
test-unit:
    stage: test-unit
    image: $CONTAINER_IMAGE
    services: 
        - MySql:5.7
    script:
        - echo "Unit-test"
        - python test.py
       
        

release:
    stage: release
    script:
        - echo "Realese"
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
        - docker pull $CONTAINER_IMAGE
        - docker tag $CONTAINER_IMAGE $CONTAINER_RELEASE_IMAGE
        - docker push $CONTAINER_RELEASE_IMAGE


deploy:
    stage: deploy
    image: ruby:latest
    script:
        - apk update && apk add git
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_NAME_PROJECT --api-key=$HEROKU_API_KEY