image: docker:stable 

services:
    - docker:dind

#Environment variables
variables:
    CONTAINER_IMAGE: registry.gitlab.com/jimmy.exe/2019_assignment1_balducci_guidi
 #MYSQL_ROOT_PASSWORD: root
 #MYSQL_DATABASE: 
  #CONTAINER_RELEASE_IMAGE: registry.gitlab.com/Jimmy.exe/2019_assignment1_balducci_guidi:latest

#stages
stages:
    - build
    - verify
    - test-unit
build:
    stage: build
    script:
        - echo "Building"
        - echo $CI_JOB_TOKEN
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
        - docker build -t $CONTAINER_IMAGE .
        - docker push $CONTAINER_IMAGE
verify:
    stage: verify
    image: $CONTAINER_IMAGE
    script:
        - pylint userapp.py
        - pylint back_database.py
        - pylint check_functions.py
test-unit:
    stage: test-unit
    image: $CONTAINER_IMAGE
    #services: 
    #    - MySql:5.7
    script:
        -python test.py

